apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote-app
  name: vote-app
  namespace: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote-app
  template:
    metadata:
      labels:
        app: vote-app
    spec:
      containers:
      - image: ngnix
        name: vote-app
        ports:
        - containerPort: 80
          name: vote-app
